### ISSUE TITLE
Warning vue router

### ISSUE THREAD

**Issue by javialon26** [nuxt-community/nuxt-i18n#57]
In all routes with more than one level i have this warning:

```[vue-router] Route with name 'usuario-editar-perfil-es-es' does not exist```

Examples:

Route: http://localhost:3000/usuario/editar-perfil
[vue-router] Route with name 'usuario-editar-perfil-es-es' does not exist

Route: http://localhost:3000/usuario/mis-anuncios
[vue-router] Route with name 'usuario-mis-anuncios-es-es' does not exist

But in routes with only one level it is okay, for example:

http://localhost:3000/ayuda
http://localhost:3000/quienes-somos

My Nuxt version is 1.4.0 and nuxt-i18n version is 2.9.1.
Configurations:
```
  defaultLocale: 'es',
  locales: [
    {
      code: 'es',
      iso: 'es-ES',
      name: 'Español',
      langFile: 'es-ES.js'
    },
    {
      code: 'en',
      iso: 'en-US',
      name: 'English',
      langFile: 'en-US.js'
    }
  ],
  loadLanguagesAsync: true,
  langDir: 'locales/'
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxt-i18n/issues/c46">#c46</a>)</em></sub></div>

**Comment by paulgv** [comment]
Hi @javialon26, what does the files structure look like in your pages directory?

**Comment by javialon26** [comment]
@paulgv this is the pages directory and now the same warning happens with all pages inside ayuda directory

![screenshot from 2018-03-28 11 04 30](https://user-images.githubusercontent.com/8138654/38034583-fcb969d2-3278-11e8-8c30-650a4600b734.jpeg)

**Comment by MoeCasts** [comment]
I fixed the problem by rewrite this code.

[https://github.com/nuxt-community/nuxt-i18n/blob/38325e2a0b49b2abe25a6abaed663fa3aa7f27f4/lib/templates/i18n.routing.middleware.js#L37](url)

const routeName = route && route.name ? app.getRouteBaseName() : 'index';

**Comment by javialon26** [comment]
After the update the warning is still showing but i found the problem.

I have a custom breadcrumb component with a localePath method in a nuxt-link tag. The name param is taken from the store and the value is loaded in a middleware with the value of route.name, this value already has -es or -en suffix and when is passed to localePath the suffix is added again.

This will be fixed or i need to take care of this in my own code?

Thank you!

**Comment by javialon26** [comment]
any news on this?

**Comment by paulgv** [comment]
Hi @javialon26 !
Sorry I've not been able to spend much time on the module lately.
If your paths are already localized, you don't need to use `localePath`, you can simply pass them as is to `<nuxt-link>`, any way you could do that?

**Comment by Extarys** [comment]
I have the same issue, I opened another ticket for it though. [Can't make i18n to work (Cannot continue my project without it)](https://nuxtjs.cmty.io/nuxt-community/nuxt-i18n/issues/c69#comment-5ae0c6df9d07830014695658) - Ignore the first part I was setting it up the 'old' way (I found that 6 hours later :P)

**Comment by trylovetom** [comment]
this.$router.push(this.localPath('/path'))
doesn't work.

I get the same wronging again.

**Comment by georgefeast** [comment]
@paulgv I'm still experiencing this issue with the '[vue-router] Route with name x does not exist' whenever I manually set enabled locales in the component. It seems the error is generated in every case where localePath is used: the only way to get rid of the warnings altogether is if I set SEO: false, remove all links with localePath and remove the language switcher so it seems like a warning is generated anywhere localePath is called. Do you have any idea how to fix this? Or @MoeCasts, could you repost the change you mentioned here https://github.com/nuxt-community/nuxt-i18n/issues/57#issuecomment-379045694 ?

**Comment by pkorzh** [comment]
i have the same problem, usually happens after rebuild.

![](https://s3-eu-central-1.amazonaws.com/japanesevedro/monosnap/router.js__kaban_2018-10-28_09-12-49.png)

i was able to narrow down the problem to this code:

```
this.extendRoutes((routes) => {
  const localizedRoutes = makeRoutes(routes, {
    ...options,
    pagesDir
  })
  routes.splice(0, routes.length)
  routes.unshift(...localizedRoutes)
});
```

when rebuild starts `routes` already contains localized routes.

**Comment by cyxapb1280** [comment]
The same for me, as @pkorzh has, started after I’ve updated nuxt to v2.*

**Comment by matthieubellon** [comment]
Same here but only with hash key as @pkorzh  and @cyxapb1280 

`:to="localePath({name:'index'},$i18n.locale)"` > no warnings
`:to="localePath({name:'index', hash:"#section-prices"},$i18n.locale)"` > warnings crazy

**Comment by phortx** [comment]
So what is the solution for this issue when it's closed?

**Comment by phortx** [comment]
Found https://github.com/nuxt-community/nuxt-i18n/issues/14

**Comment by ProduceSinapsi** [comment]
> Same here but only with hash key as @pkorzh and @cyxapb1280
> 
> `:to="localePath({name:'index'},$i18n.locale)"` > no warnings
> `:to="localePath({name:'index', hash:"#section-prices"},$i18n.locale)"` > warnings crazy
> 
> Also with Nuxt 2.*, I'll try Nuxt 1
> 
> EDIT
> Seems that even without localePath that `:to="{name:'index', hash:"#section-prices"}"` triggers weird errors also

In this way I no longer see any warnings

**Comment by dilikpulatov** [comment]
`// Routes generation strategy, can be set to one of the following:
  // - 'no_prefix': routes won't be prefixed
  // - 'prefix_except_default': add locale prefix for every locale except default
  // - 'prefix': add locale prefix for every locale
  // - 'prefix_and_default': add locale prefix for every locale and default
  strategy: 'prefix_except_default',`

**Comment by tvld** [comment]
Problem still persists.  ``strategy: 'no_prefix'`` is not ideal option as you loose all links. 

But so far all I can do as ``localePath('index')`` is buggy.) I got all the time :
```
[vue-router] Route with name '/my_page___nl' does not exist vue-router.esm.js:16
```

**Comment by ianfortier** [comment]
You can fix this problem by installing [@nuxtjs/router-extras](https://github.com/nuxt-community/router-extras-module) and set a custom name for the route like this : 
![image](https://user-images.githubusercontent.com/2520657/71832360-c191fb80-3078-11ea-892d-8d87c10c6d65.png)

**Comment by Elvincth** [comment]
Same problem here `[vue-router] Route with name 'index___en'` does not exist, when would this be fix?

**Comment by dilikpulatov** [comment]
`
// router.js
// example urls: site.com/uz/users, site.com/ru/users, site.com/users


import Vue from 'vue'
import Router from 'vue-router'
import appConfig from "../config/main"
Vue.use(Router)

let list = [
  {path: '/', name: 'home', component:() => import('@/pages/home').then(m => m.default || m)},

  {path: '/test', name: 'test', component:() => import('@/pages/test').then(m => m.default || m)},

  {
    path: '/users/',
    component:() => import('@/pages/users/layout').then(m => m.default || m),
    children: [
      {path: '', name: 'users', component:() => import('@/pages/users/list').then(m => m.default || m)},
      {path: ':username', name: 'users_view', component:() => import('@/pages/users/view').then(m => m.default || m)},
      {path: ':username/:posts', name: 'users_posts', component:() => import('@/pages/users/posts').then(m => m.default || m)},
    ]
  }
]

let routes = []

for (let i in list) {
  let item = list[i]

  if (typeof item.children !== 'undefined') {

    for (let l in appConfig.languageList) { // "languageList": ["ru", "uz"]
      let lang = appConfig.languageList[l]
      let childes = [], path = item.path

      for (let c in item.children) {
        let child = item.children[c]
        childes.push({
          path: child.path,
          name: `${child.name}___${lang}`,
          component: child.component
        })
      }

      if (lang !== appConfig.defaultLanguage) { //  "defaultLanguage": "ru"
        path = `/${lang}${item.path}`
      }

      routes.push({
        path,
        component: item.component,
        children: childes
      })
    }
  } else {
    generateLangRoute(item)
  }
}

function generateLangRoute(item, childes = []) {
  for (let l in appConfig.languageList) {
    let lang = appConfig.languageList[l]
    let x = {
      component: item.component
    }

    if (typeof item.name !== 'undefined') {
      x.name = `${item.name}___${lang}`
    }

    if (childes.length !== 0) {
      x.children = childes
    }

    if (lang === appConfig.defaultLanguage) {
      x.path = item.path
    } else {
      x.path = `/${lang}${item.path}`
    }

    routes.push(x)
  }
}


export function createRouter(){
  const home_url = "home";
  const router = new Router({
    mode: 'history',
    routes
  })

  return router
}

`

**Comment by dilikpulatov** [comment]
![Снимок экрана от 2021-02-27 04-25-53](https://user-images.githubusercontent.com/33443186/109366219-a7d2f980-78b4-11eb-8ad4-c382f758628f.png)
![Снимок экрана от 2021-02-27 04-26-33](https://user-images.githubusercontent.com/33443186/109366222-aa355380-78b4-11eb-93a7-4111fb09311c.png)
![Снимок экрана от 2021-02-27 04-26-50](https://user-images.githubusercontent.com/33443186/109366225-abff1700-78b4-11eb-84b2-3909c137a6c3.png)

**Comment by jwittekind** [comment]
@paulgv The described issue in this thread is still existent, though it got closed.
Unfortunately there is no documented solution or reason which solves the mentioned issue.
Why is this ticket closed? Can we expect a bugfix for this within this i18n module or is there any specific implementation of how to avoid the output of countless warnings?

**Comment by rchl** [comment]
This issue is very old and a lot has changed since the initial report so I'm not sure if your issue is even related.

Please create a new issue for your problem with a reproduction repo (or codesandbox).

**Comment by jonalxh** [comment]
Is is still happening with the latest version of nuxt and router.

**Comment by adhamfarrag** [comment]
@paulgv we just need to disable the warnings. 2022 and it's still going on.

**Comment by renaudham** [comment]
to all, in my case it was just  about  redoing a npm run dev / build and all  is ok

**Comment by codeDevStory** [comment]
This continued on August 9, 2023@paulgv

**Comment by surge-squirrel** [comment]
This continued on August 9, 2023 @paulgv
